services:
  redis:
    image: redis:latest
    networks:
      - app-network

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
    depends_on:
      - redis
    networks:
      - app-network

  beat:
    build: .
    command: celery -A tasks beat --loglevel=info
    volumes: 
      - ./app:/app
    depends_on:
      - celery
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
